name: "Package"

on:
    push:
    workflow_dispatch: # Allow on demand execution
    pull_request:
        # The branches below must be a subset of the branches above
        branches: [master]

jobs:
    build:
        name: Build and Package
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Publish to NuGet
              uses: brandedoutcast/publish-nuget@v2.5.5
              with:
                  PROJECT_FILE_PATH: src/DotLiquid/DotLiquid.csproj
                  PACKAGE_NAME: DotLiquid-Net6
                  NUGET_KEY: ${{secrets.NUGET_API_KEY}}
