name: "Unit Tests"

on:
    push:
    pull_request:
        # The branches below must be a subset of the branches above
        branches: [master]
    workflow_dispatch: # Allow on demand execution

jobs:
    test:
        name: Unit Tests
        uses: ./.github/workflows/build_verification_dotnet.yml
        with:
            project_path: ./src
            use_submodules: false
            run_tests: true
        secrets: inherit
